In [1]:
import pandas as pd

In [10]:
detail = pd.read_parquet("../data/2021/3/15/21305-0.parquet")

In [7]:
totals = pd.read_parquet("../data/App10.parquet")
totals.head()
totals.columns

Index(['uid', 'jobid', 'start_time', 'end_time', 'darshan_log_version', 'exe',
       'nprocs', 'runtime', 'total_BGQ_CSJOBID', 'total_BGQ_NNODES',
       ...
       'total_STDIO_F_WRITE_START_TIMESTAMP',
       'total_STDIO_F_READ_START_TIMESTAMP',
       'total_STDIO_F_OPEN_END_TIMESTAMP', 'total_STDIO_F_CLOSE_END_TIMESTAMP',
       'total_STDIO_F_WRITE_END_TIMESTAMP', 'total_STDIO_F_READ_END_TIMESTAMP',
       'total_STDIO_F_FASTEST_RANK_TIME', 'total_STDIO_F_SLOWEST_RANK_TIME',
       'total_STDIO_F_VARIANCE_RANK_TIME',
       'total_STDIO_F_VARIANCE_RANK_BYTES'],
      dtype='str', length=481)

In [9]:
totals['timestamp'] = pd.to_datetime(totals['start_time'],unit='s')
totals.loc[:,['jobid', 'timestamp', 'start_time']]

     jobid           timestamp  start_time
1   629684 2021-01-07 20:07:22  1610050042
1   629672 2021-01-07 05:40:44  1609998044
0   639961 2021-01-08 00:29:47  1610065787
0   629691 2021-01-08 04:10:12  1610079012
1   629686 2021-01-07 22:53:32  1610060012
..     ...                 ...         ...
1   812813 2021-03-13 12:36:13  1615638973
0   812795 2021-03-13 12:35:47  1615638947
0   812739 2021-03-13 11:03:14  1615633394
0   813036 2021-03-13 15:43:20  1615650200
0   805133 2021-03-14 04:08:23  1615694903

[8047 rows x 3 columns]

In [11]:
detail['timestamp'] = pd.to_datetime(detail['start_time'],unit='s')
detail.loc[:,['jobid', 'timestamp', 'start_time']]

     jobid           timestamp  start_time
0    21305 2021-03-15 21:41:01  1615844461
1    21305 2021-03-15 21:41:01  1615844461
2    21305 2021-03-15 21:41:01  1615844461
3    21305 2021-03-15 21:41:01  1615844461
4    21305 2021-03-15 21:41:01  1615844461
..     ...                 ...         ...
632  21305 2021-03-15 21:41:01  1615844461
633  21305 2021-03-15 21:41:01  1615844461
634  21305 2021-03-15 21:41:01  1615844461
635  21305 2021-03-15 21:41:01  1615844461
636  21305 2021-03-15 21:41:01  1615844461

[637 rows x 3 columns]